### ISSUE TITLE
Rename to postcss-pixel-imperfect?

### ISSUE THREAD

**Issue by chicoxyzzy** [shitjs/postcss-pixel-imperfect#1]
Current name is to rude. Maybe we can rename it to something more friendly like `postcss-pixel-imperfect`? What do you think about this idea, comrades?

**Comment by denysdovhan** [comment]
SGMT

**Comment by denysdovhan** [comment]
BTW, there should be a README with good explanation and screenshots.

**Comment by ghaiklor** [comment]
LGTM, maybe @vslinko will rename it on his own as an author, or we can do by ourselves.

**Comment by vslinko** [comment]
Renamed
